# Generated by Django 4.0.9 on 2023-02-10 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('stage', models.CharField(max_length=255)),
                ('digi_type', models.CharField(max_length=255)),
                ('attribute', models.CharField(max_length=255)),
                ('level', models.IntegerField(null=True)),
                ('play_cost', models.IntegerField(null=True)),
                ('evolution_cost', models.IntegerField(null=True)),
                ('cardrarity', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255, null=True)),
                ('dp', models.IntegerField(blank=True, null=True)),
                ('cardnumber', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('maineffect', models.TextField(blank=True, null=True)),
                ('sourceeffect', models.TextField(blank=True, null=True)),
                ('set_name', models.CharField(max_length=255)),
                ('card_sets', models.TextField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('passwd', models.CharField(max_length=255)),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=255)),
                ('expiracion', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deckbuilder.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deckbuilder.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deckbuilder.deck')),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(through='deckbuilder.DeckCard', to='deckbuilder.card'),
        ),
    ]
