# Generated by Django 4.0.9 on 2023-02-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deckbuilder', '0002_alter_card_attribute_alter_card_digi_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cardrarity',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
